### ISSUE TITLE
You can enter more than 200 characters

### ISSUE THREAD

**Issue by Taha-Hassan-Git** [fac27/fess-booth#52] opened 2023-05-17 16:02 UTC
Loooooove the gradients.

Confessions can be submitted with more than 200 characters.

Random emoji assignment is siiiiick.

**Comment by zakkariyaa** [comment] 2023-05-18 10:36
Hi, Taha. Thanks for the kind words.
Great catch. Our textarea attribute maxlength got lost in a merge conflict and the issue is fixed now.

**Closed** 2023-05-18 10:36 UTC
